defaults:
  - maniskill_gs   
  - _self_           

name: maniskill_gs_stack
<<<<<<< HEAD
num_gaussians: 1024
min_opacity: 0.9

shape_meta: &shape_meta
  obs:
    gs_positions:
      shape: 
        - ${task.num_gaussians}
        - 3
      type: spatial
    point_cloud:          # for running dp3 on gsplat means
      shape: 
        - ${task.num_gaussians}
        - 3
      type: spatial
    gs_rotations_9d:
      shape: 
        - ${task.num_gaussians}
        - 9
      type: spatial
    gs_surface_normals:   # trying to use surface normals instead of rotation matrices
      shape: 
        - ${task.num_gaussians}
        - 3
      type: spatial
    gs_log_scales:
      shape: 
        - ${task.num_gaussians}
        - 3
      type: spatial
    gs_opacities:
      shape: 
        - ${task.num_gaussians}
        - 1
      type: spatial
    gs_rgb:
      shape: 
        - ${task.num_gaussians}
        - 3
      type: spatial 
=======
>>>>>>> origin/PixiPwr

env_runner:
  _target_: diffusion_policy_3d.env_runner.maniskill_gs_runner.GSManiSkillRunner
  task_name: StackFr3Env-v1
  num_gaussians: ${task.num_gaussians}
  min_opacity: ${task.min_opacity}
  use_gsplat_viewer: false
  scene_gs_cfg_name: "fr3_stack_with_normals"
  representation_space: ${task.representation_space}

dataset:
  _target_: diffusion_policy_3d.dataset.maniskill_gs_dataset.GSManiskillDataset
  zarr_path: /home/max/projects/gsplat_policy/datasets/gsplat_3d_diffusion_policy/stack
  representation_space: ${task.representation_space}

train_data_augmentations:
  - _target_: diffusion_policy_3d.dataset.data_augmentations.HighOpacityActiveGaussianRandomSampling
    num_samples: ${task.num_gaussians}
    min_opacity: ${task.min_opacity}
  # - _target_: diffusion_policy_3d.dataset.data_augmentations.GaussianFPSAndBallQuery
  #   num_samples: ${task.num_gaussians}
  #   random_start_point: True
  #   radius: 0.01
  #   max_neighbors: 128

val_data_augmentations:
  - _target_: diffusion_policy_3d.dataset.data_augmentations.HighOpacityActiveGaussianRandomSampling
    num_samples: ${task.num_gaussians}
    min_opacity: ${task.min_opacity}
  # - _target_: diffusion_policy_3d.dataset.data_augmentations.GaussianFPS
  #   num_samples: ${task.num_gaussians}
  #   random_start_point: False
