defaults:
  - maniskill_gs_stack  
  - _self_              

name: maniskill_wrist_cam_gs_stack

env_runner:
  _target_: diffusion_policy_3d.env_runner.maniskill_wrist_cam_gs_runner.WristCamGSManiSkillRunner
  task_name: StackFr3WristCamEnv-v1

dataset:
  _target_: diffusion_policy_3d.dataset.maniskill_wrist_cam_gs_dataset.WristCamGSManiskillDataset
  zarr_path: /home/max/projects/gsplat_policy/datasets/gsplat_3d_diffusion_policy/stack_wrist_cam_positions_surf_normals_active_gaussians_mask_semantics

train_augmentations:
  - _target_: diffusion_policy_3d.dataset.data_augmentations.GaussianRandomSample
    num_samples: ${task.dataset.num_gaussians}
  # - _target_: diffusion_policy_3d.dataset.data_augmentations.GaussianFPSAndBallQuery
  #   num_samples: ${task.dataset.num_gaussians}
  #   random_start_point: True
  #   radius: 0.01
  #   max_neighbors: 128

eval_augmentations:
  - _target_: diffusion_policy_3d.dataset.data_augmentations.GaussianRandomSample
    num_samples: ${task.dataset.num_gaussians}
  # - _target_: diffusion_policy_3d.dataset.data_augmentations.GaussianFPS
  #   num_samples: ${task.dataset.num_gaussians}
  #   random_start_point: False
