defaults:
  - maniskill_gs   
  - _self_           

name: maniskill_gs_stack

env_runner:
  _target_: diffusion_policy_3d.env_runner.maniskill_gs_runner.GSManiSkillRunner
  task_name: StackFr3Env-v1
  num_gaussians: ${task.num_gaussians}
  use_gsplat_viewer: false
  scene_gs_cfg_name: "fr3_stack_with_normals"

dataset:
  _target_: diffusion_policy_3d.dataset.maniskill_gs_dataset.GSManiskillDataset
  zarr_path: /home/max/projects/gsplat_policy/datasets/gsplat_3d_diffusion_policy/stack
  num_gaussians: ${task.num_gaussians}
