defaults:
  - base_dp3
  - override task: maniskill_stack
  - _self_

name: train_dp3

policy:   # pcd-specific params
  use_point_crop: true   # anchor for ${policy.use_point_crop} in the legacy metaworld/adroit/dexart task configs
  use_pc_color: false
  pointnet_type: "pointnet"
  pointcloud_encoder_cfg:
    in_channels: 3
    out_channels: ${policy.encoder_output_dim}
    use_layernorm: true
    final_norm: layernorm # layernorm, none
    normal_channel: false
