defaults:
  - base_dp3
  - override task: maniskill_gs_stack
  - _self_

name: train_gsplat_dp3

policy:
  _target_: diffusion_policy_3d.policy.gsplat_dp3.GSplatDP3
  encoder_output_dim: 64     # 128
  use_state_features: true

  # Gaussian Splatting parameters
  gsplat_encoder_cfg:
    encoder_type: raw_concat               # Options: latent_concat, raw_concat
    
    # ── Config for latent_concat (projection mlps for params) ──
    param_keys_feature_dims: # defines which param groups to encode to which feature dim 
      gs_positions: 64         
      gs_rotations_9d: 0       # 0 disables (previously 64)
      gs_surface_normals: 64    
      gs_log_scales: 0         
      gs_opacities: 0          
      gs_rgb: 0                

    # ── Config for raw_concat (which parameters to use) ──
    raw_keys:         
      - gs_positions
      - gs_surface_normals

    backbone_channels: [256, 512, 1024]     # in DP3 with XYZRGB-Encoder [64, 128, 256, 512]
    use_layernorm: true                     # in backbone
    use_projection: true                    # projection to out_channels
    final_norm: layernorm                   # within projection
    out_channels: ${policy.encoder_output_dim}    
